# Generated by Django 4.1.7 on 2023-04-25 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_remove_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='banner',
            field=models.ImageField(null=True, upload_to='movies/', verbose_name='Banner'),
        ),
    ]
