# Generated by Django 4.1.7 on 2023-04-25 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='Черновик'),
        ),
        migrations.AddField(
            model_name='post',
            name='url',
            field=models.SlugField(max_length=130, null=True, unique=True),
        ),
    ]
