# Generated by Django 4.1.7 on 2023-04-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_post_draft_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='banner',
            field=models.ImageField(null=True, upload_to='posts/', verbose_name='Banner'),
        ),
    ]
