# Generated by Django 4.1.7 on 2023-04-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
